### ISSUE TITLE
Use quickfix for compilation output

### ISSUE THREAD

**Issue by Shatur** [lanza/vim-cmake#2]
Currently this plugin uses terminal for compilation output. But I suggest to use quickfix window for that because it will allow to parse errors. For example, asynctasks plugin allows to [specify error format](https://github.com/skywind3000/asynctasks.vim#build-and-run-a-single-file) and parses it:
![example](https://camo.githubusercontent.com/6b3472cf7d40746815313aa55fdccbe196c1d7a6/68747470733a2f2f736b7977696e64333030302e6769746875622e696f2f696d616765732f702f6173796e637461736b732f64656d6f2d312e706e67)
It allows to jump between error locations like in regular IDE.

**Comment by lanza** [comment]
It used to be that way, but I found the build log was much more readable in  a vertical split. I'll look into making the output an option to reenable this.

**Comment by Shatur** [comment]
> It used to be that way, but I found the build log was much more readable in a vertical split. I'll look into making the output an option to reenable this.

This would be good. But I meant that use quickfix window instead of terminal because it will allow to navigate between errors occured in files.

**Comment by lanza** [comment]
Yea I understand. I had that until recently, I just found that my normal workflow was reading the build log and going to the line/column manually and not navigating via the quick fix.

I think `git checkout 5c469fe57ba54cdafc1c2cb4e7b63d739edae146~1` will do what you want.

**Comment by Shatur** [comment]
I tested on this commit, but this is not a quickfix window.
![изображение](https://user-images.githubusercontent.com/22453358/78506329-8e4b2f80-7781-11ea-9354-ee2c1db6572b.png)

**Comment by lanza** [comment]
So that commit uses `vim-dispatch`'s `Make` command which will run the command in a split but will then load the results in a quick fix. 

```
:Make [arguments]       Using the current |:compiler| settings, dispatch a
                        build in the foreground.  Adapter strategies vary, but
                        the goal is visibility without stealing focus.  When
                        the build is complete, load the results into the
                        |quickfix| list and call |:cwindow|.  This command is
                        preferred for shorter tasks like "build this file."
```

Put an error in your code and do `CMakeBuildAll` and it'll build in a split and then show the errors in the `QuickFix` pane.

Although, this actually doesn't work now that I look at it. The vim compiler settings aren't realizing the output from the build invocation has `pwd` of `build/Debug` and is applying the `../..` incorrectly.

**Comment by lanza** [comment]
Okay I added a `g:vim_cmake_build_tool` setting which switches over this value to use a specific build tool. `g:vim_cmake_build_tool = 'make'` seems to be what you want.

**Comment by Shatur** [comment]
~~Tested, but it not fills quickfix with errors with `g:vim_cmake_build_tool = 'make'`~~

It works, thank you!
But only for BuildAll, is it possible to add such ability for BuildTarget?

**Comment by Shatur** [comment]
Is it also possible to display compilation output in quickfix directly instead of toggling output and opening quickfix? Or it depends on used build tool?

**Comment by lanza** [comment]
I added it for `CMakeBuildCurrentTarget` and `CMakePickAndBuildTarget`. `CMakeBuildTarget` was renamed to `CMakePickAndBuildTarget` because the name was ambiguous compared to `CMakeBuildCurrentTarget`. LMK if there are any problems.

> Is it also possible to display compilation output in quickfix directly instead of toggling output and opening quickfix? Or it depends on used build tool?

I don't believe so. You fill the quick fix list with `:cexpr someexpr` which runs the expression and simple puts the text in the quick fix buffer. i'm sure it's technically possible to incrementally fill the quick fix list with some constantly updating buffer contents but that seems really hacky.

**Comment by Shatur** [comment]
Thanks!

**Comment by Shatur95** [comment]
> I don't believe so. You fill the quick fix list with :cexpr someexpr which runs the expression and simple puts the text in the quick fix buffer. i'm sure it's technically possible to incrementally fill the quick fix list with some constantly updating buffer contents but that seems really hacky.

[AsyncRun](https://github.com/skywind3000/asyncrun.vim) somehow fill quickfix... Is it use a hack?
